lang: en
languages_i:
  en: 0
  zh: 1
languages: [ 'english', '中文' ]
switched_languages: [ '中文', 'english' ]
switched_languages_subpath: [ '/zh', '/en' ]

title:
  - Chen, Guowei space
  - 陈国威的拾贝室
author:
  - Chen, Guowei
  - 陈国威
description:
  - a good coder just like a firefly in the dark
  - 识石马者就像漆黑中的萤火虫

owner: icgw.space
email: icgw@outlook.com

baseurl: ''
url: 'https://icgw.space'

github_user: 'icgw'

navigations:
  - text: [ 'moments', '时刻' ]
    url: [ '/en/moments/list.html', '/zh/moments/list.html' ]
  - text: [ 'memoirs', '记忆' ]
    url: [ '/en/memoirs/list.html', '/zh/memoirs/list.html' ]
