lang: en
languages_i:
  en: 0
  zh: 1

languages: [ 'english', '中文' ]
switched_languages: [ '中文', 'english' ]

languages_subpath: [ '/en', '/zh' ]
switched_languages_subpath: [ '/zh', '/en' ]

title:
  - G.C. | Good Coder
  - 囗囗 | 知石马者
author:
  - Chen, Guowei
  - 陈国威
description:
  - a good coder just like a firefly in the dark
  - 识石马者就像漆黑中的萤火虫

owner: icgw.space
email: icgw@outlook.com

baseurl: ''
url: 'https://icgw.space'

github_user: 'icgw'

navigations:
  - text: [ 'home', '首页' ]
    url: [ '/en/index.html', '/zh/index.html' ]
  - text: [ 'moments', '时刻' ]
    url: [ '/en/moments/list.html', '/zh/moments/list.html' ]
  - text: [ 'memoirs', '记忆' ]
    url: [ '/en/memoirs/list.html', '/zh/memoirs/list.html' ]
